#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

apt-get install ufw
sudo ufw status
sudo ufw default allow outgoing
sudo ufw default deny incoming
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw allow ssh
sudo ufw enable
sudo ufw allow 80/tcp comment 'accept Apache'
sudo ufw allow 443/tcp comment 'accept HTTPS connections'